# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Iceroad
email: rosy.m.tucker@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The personal website of Rose Tucker, London software developer, with ThoughtWorks.

baseurl: "" # the subpath of your site, e.g. /blog

url: "http://iceroad.co.uk"

author_avatar: https://pbs.twimg.com/profile_images/511434362743554048/38wGSMo1.jpeg
twitter_username: Rosy_Tucker
github_username: RosyTucker
linkedin_username: tuckerrose

# Build settings
markdown: kramdown

permalink: :categories/:year/:title/